package qmmt.model;

public enum QuantumGatesEnum {
        CCX("CCX",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        CH("CH", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        CP("CP", new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx", "rzz",
                        "u2" }),
        CRX("CRX",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        CRY("CRY",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        CRZ("CRZ",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        CSWAP("CSWAP",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        CSX("CSX",
                        new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz",
                                        "swap", "u1" }),
        CU("CU", new String[] { "u3" }),
        CU1("CU1",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        CU3("CU3", new String[] { "u" }),
        CX("CX", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        CY("CY", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        CZ("CZ", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        DCX("DCX",
                        new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz",
                                        "swap", "u1" }),
        H("H", new String[] { "id", "t", "tdg", "x", "h", "i", "sdg", "s", "y", "z", "sx" }),
        I("I", new String[] { "t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id" }),
        ID("ID", new String[] { "t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id" }),
        ISWAP("ISWAP",
                        new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz",
                                        "swap", "u1" }),
        MS("MS", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        P("P", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        R("R", new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx", "rzz",
                        "u2" }),
        RX("RX", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        RXX("RXX",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        RY("RY", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        RYY("RYY",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        RZ("RZ", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        RZX("RZX",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        RZZ("RZZ",
                        new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx",
                                        "rzz", "u2" }),
        S("S", new String[] { "t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id" }),
        SDG("SDG", new String[] { "t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id" }),
        SWAP("SWAP",
                        new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz",
                                        "swap", "u1" }),
        SX("SX", new String[] { "id", "t", "tdg", "x", "h", "i", "s", "sdg", "y", "z", "sx" }),
        T("T", new String[] { "t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id" }),
        TDG("TDG", new String[] { "t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id" }),
        U("U", new String[] { "u", "u3" }),
        U1("U1", new String[] { "ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry", "rz", "swap",
                        "u1" }),
        U2("U2", new String[] { "ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy", "rzx", "rzz",
                        "u2" }),
        U3("U3", new String[] { "u", "u3" }),
        X("X", new String[] { "x", "t", "tdg", "h", "i", "sx", "s", "sdg", "y", "z", "id" }),
        Y("Y", new String[] { "t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id" }),
        Z("Z", new String[] { "t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id" });

        /*
         * 
         * "ch": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "cp": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "crx": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "cry": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "crz": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "cswap": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx",
         * "ryy", "rzx", "rzz", "u2"},
         * "csx": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "cu": set(),
         * "cu1": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "cu3": set(),
         * "cx": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "cy": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "cz": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "dcx": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "h": {"id", "t", "tdg", "x", "h", "i", "sdg", "s", "y", "z", "sx"},
         * "i": {"t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id"},
         * "id": {"t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id"},
         * "iden": set(),
         * "iswap": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx",
         * "ry", "rz", "swap", "u1"},
         * "ms": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "p": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "r": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "rx": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "rxx": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "ry": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "ryy": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "rz": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "rzx": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "rzz": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "s": {"t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id"},
         * "sdg": {"t", "tdg", "x", "h", "i", "sx", "sdg", "s", "y", "z", "id"},
         * "swap": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx",
         * "ry", "rz", "swap", "u1"},
         * "sx": {"id", "t", "tdg", "x", "h", "i", "s", "sdg", "y", "z", "sx"},
         * "t": {"t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id"},
         * "tdg": {"t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id"},
         * "u": {"u", "u3"},
         * "u1": {"ch", "csx", "cx", "cy", "cz", "dcx", "iswap", "ms", "p", "rx", "ry",
         * "rz", "swap", "u1"},
         * "u2": {"ccx", "cp", "crx", "cry", "crz", "cswap", "cu1", "r", "rxx", "ryy",
         * "rzx", "rzz", "u2"},
         * "u3": {"u", "u3"},
         * "x": {"x", "t", "tdg", "h", "i", "sx", "s", "sdg", "y", "z", "id"},
         * "y": {"t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id"},
         * "z": {"t", "tdg", "x", "h", "i", "sx", "s", "sdg", "y", "z", "id"}}
         */
        String quantumGate;
        String[] equivalences;

        QuantumGatesEnum(String quantumGate, String[] equivalences) {
                this.quantumGate = quantumGate;
                this.equivalences = equivalences;
        }

        public String[] getEquivalences() {
                return equivalences;
        }

        public void setEquivalences(String[] equivalences) {
                this.equivalences = equivalences;
        }

        public String getQuantumGate() {
                return quantumGate;
        }

        public void setQuantumGate(String quantumGate) {
                this.quantumGate = quantumGate;
        }

}
